# Generated by Django 4.2.6 on 2023-10-25 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=80)),
                ('nationality', models.CharField(choices=[('I', 'Internal'), ('E', 'External')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=14, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Number of roadway')),
                ('roadway', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year_of_publish', models.DateTimeField(blank=True, help_text='The time of publish book')),
                ('publisher', models.CharField(blank=True, max_length=250)),
                ('ISBN_code', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author')),
                ('cage_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.cage')),
            ],
        ),
    ]
