# Generated by Django 4.2.6 on 2023-10-25 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Number of roadway'),
        ),
        migrations.AlterField(
            model_name='cage',
            name='roadway',
            field=models.CharField(max_length=250, verbose_name='A title for roadway'),
        ),
    ]
