# Generated by Django 4.2.6 on 2023-10-25 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_cage_number_alter_cage_roadway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='cage number'),
        ),
    ]
