# Generated by Django 4.2.6 on 2023-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_cage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_publish',
            field=models.DateField(blank=True, help_text='The time of publish book'),
        ),
    ]
